# Generated by Django 3.0.7 on 2020-09-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='new_cases',
            new_name='county_new_cases',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='new_deaths',
            new_name='county_new_deaths',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='total_cases',
            new_name='county_total_cases',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='total_deaths',
            new_name='county_total_deaths',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='total_tests',
            new_name='county_total_tests',
        ),
        migrations.AddField(
            model_name='college',
            name='college_total_tests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
