# Generated by Django 3.0.7 on 2020-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200928_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_total_tests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
