# Generated by Django 3.0.7 on 2020-09-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200928_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_total_tests',
            new_name='college_total_cases',
        ),
    ]
