# Generated by Django 3.0.7 on 2020-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_california'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_total_cases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
