# Generated by Django 3.0.7 on 2020-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200928_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='county_new_deaths',
        ),
        migrations.AddField(
            model_name='college',
            name='county_active_cases',
            field=models.TextField(default='N/A'),
        ),
    ]
